### ISSUE TITLE
Exception thrown on AEM 6.2

### ISSUE THREAD

**Issue by davidjgonzalez** [Adobe-Marketing-Cloud/aem-htl-repl#20]
Breaking exception thrown during evaluation of server-side JS:
-  Promise has completed with failure: Error: No resource found at path: /var/classes/sightly

```
 <div id="java" class="output-view editor hidden"
<h1>Error during include of component '/apps/repl/components/repl'</h1><h3>Error Message:</h3>
<pre>org.apache.sling.api.scripting.ScriptEvaluationException: org.apache.sling.scripting.sightly.SightlyException: Promise has completed with failure: Error: No resource found at path: /var/classes/sightly</pre><h3>Processing Info:</h3>
<table style='font-family: monospace'>
<tr><td>Page</td><td>=</td><td>/content/repl<td></tr><tr><td>Resource Path</td><td>=</td><td>/content/repl/jcr:content<td></tr><tr><td>Cell</td><td>=</td><td>repl<td></tr><tr><td>Cell Search Path</td><td>=</td><td>repl<td></tr><tr><td>Component Path</td><td>=</td><td>/apps/repl/components/repl<td></tr></table>
<h3>Sling Request Progress:</h3>
<pre>
      0 TIMER_START{Request Processing}
      0 COMMENT timer_end format is {&lt;elapsed msec&gt;,&lt;timer name&gt;} &lt;optional message&gt;
      0 LOG Method=GET, PathInfo=/content/repl.html
      0 TIMER_START{ResourceResolution}
      0 TIMER_END{0,ResourceResolution} URI=/content/repl.html resolves to Resource=JcrNodeResource, type=cq:Page, superType=null, path=/content/repl
      0 LOG Resource Path Info: SlingRequestPathInfo: path='/content/repl', selectorString='null', extension='html', suffix='null'
      0 TIMER_START{ServletResolution}
      0 TIMER_START{resolveServlet(/content/repl)}
      1 TIMER_END{1,resolveServlet(/content/repl)} Using servlet /libs/cq/Page/Page.jsp
      1 TIMER_END{1,ServletResolution} URI=/content/repl.html handled by Servlet=/libs/cq/Page/Page.jsp
      1 LOG Applying Requestfilters
      1 LOG Calling filter: com.adobe.granite.resourceresolverhelper.impl.ResourceResolverHelperImpl
      1 LOG Calling filter: org.apache.sling.bgservlets.impl.BackgroundServletStarterFilter
      1 LOG Calling filter: com.adobe.granite.rest.impl.servlet.ApiResourceFilter
      1 LOG Calling filter: org.apache.sling.i18n.impl.I18NFilter
      1 LOG Calling filter: com.adobe.granite.httpcache.impl.InnerCacheFilter
      1 LOG Calling filter: org.apache.sling.rewriter.impl.RewriterFilter
      1 LOG Calling filter: com.adobe.cq.mcm.campaign.servlets.CampaignCopyTracker
      1 LOG Calling filter: com.day.cq.wcm.core.impl.WCMRequestFilter
      1 LOG Calling filter: com.adobe.cq.history.impl.HistoryRequestFilter
      1 LOG Calling filter: com.adobe.granite.optout.impl.OptOutFilter
      1 LOG Calling filter: com.day.cq.wcm.foundation.forms.impl.FormsHandlingServlet
      1 LOG Calling filter: com.adobe.cq.social.commons.cors.CORSAuthenticationFilter
      1 LOG Calling filter: com.day.cq.analytics.provisioning.impl.UserAuthenticationRequestFilter
      1 LOG Calling filter: org.apache.sling.engine.impl.debug.RequestProgressTrackerLogFilter
      1 LOG Calling filter: com.day.cq.wcm.mobile.core.impl.redirect.RedirectFilter
      1 LOG RedirectFilter did not redirect (not redirecting in author mode)
      1 LOG Calling filter: com.day.cq.wcm.core.impl.warp.TimeWarpFilter
      1 LOG Calling filter: com.day.cq.wcm.core.impl.AuthoringUIModeServiceImpl
      1 LOG Calling filter: org.apache.sling.security.impl.ContentDispositionFilter
      1 LOG Calling filter: com.adobe.granite.csrf.impl.CSRFFilter
      1 LOG Calling filter: com.adobe.granite.requests.logging.impl.RequestLoggerImpl
      1 LOG Calling filter: com.day.cq.dam.core.impl.servlet.ActivityRecordHandler
      1 LOG Calling filter: com.day.cq.dam.core.impl.assetlinkshare.AdhocAssetShareAuthHandler
      1 LOG Calling filter: com.adobe.cq.social.ugcbase.security.impl.SaferSlingPostServlet
      1 LOG Applying Componentfilters
      1 LOG Calling filter: com.day.cq.wcm.core.impl.WCMComponentFilter
      1 LOG Calling filter: com.day.cq.wcm.core.impl.WCMDebugFilter
      1 LOG Calling filter: com.day.cq.personalization.impl.TargetComponentFilter
      1 TIMER_START{/libs/cq/Page/Page.jsp#0}
      1 LOG Including resource JcrNodeResource, type=repl/components/repl, superType=null, path=/content/repl/jcr:content (SlingRequestPathInfo: path='/content/repl/jcr:content', selectorString='null', extension='html', suffix='null')
      1 TIMER_START{resolveServlet(/content/repl/jcr:content)}
      1 TIMER_END{0,resolveServlet(/content/repl/jcr:content)} Using servlet /apps/repl/components/repl/repl.html
      1 LOG Applying Includefilters
      1 LOG Calling filter: com.day.cq.wcm.core.impl.WCMDeveloperModeFilter
      1 LOG Calling filter: com.day.cq.wcm.core.impl.WCMComponentFilter
      1 LOG Calling filter: com.day.cq.wcm.core.impl.WCMDebugFilter
      1 LOG Calling filter: com.day.cq.personalization.impl.TargetComponentFilter
      1 TIMER_START{/apps/repl/components/repl/repl.html#1}
      3 LOG Found processor for post processing ProcessorConfiguration: {contentTypes=[text/html], order=-1, active=true, valid=true, processErrorResponse=true, pipeline=(generator=Config(type=htmlparser, config={}), transformers=(Config(type=linkchecker, config={}), Config(type=mobile, config=JcrPropertyMap [node=Node[NodeDelegate{tree=/libs/cq/config/rewriter/default/transformer-mobile: { jcr:primaryType = nt:unstructured, component-optional = true}}], values={jcr:primaryType=nt:unstructured, component-optional=true}]), Config(type=mobiledebug, config=JcrPropertyMap [node=Node[NodeDelegate{tree=/libs/cq/config/rewriter/default/transformer-mobiledebug: { jcr:primaryType = nt:unstructured, component-optional = true}}], values={jcr:primaryType=nt:unstructured, component-optional=true}]), Config(type=contentsync, config=JcrPropertyMap [node=Node[NodeDelegate{tree=/libs/cq/config/rewriter/default/transformer-contentsync: { jcr:primaryType = nt:unstructured, component-optional = true}}], values={jcr:primaryType=nt:unstructured, component-optional=true}]), serializer=Config(type=htmlwriter, config={}))}
     16 LOG SCRIPT ERROR: org.apache.sling.scripting.sightly.SightlyException: Promise has completed with failure: Error: No resource found at path: /var/classes/sightly
     16 TIMER_END{15,/apps/repl/components/repl/repl.html#1}
     18 TIMER_END{18,Request Processing} Dumping SlingRequestProgressTracker Entries
</pre>
<h3>Full Exception:</h3>
<pre>
org.apache.sling.api.scripting.ScriptEvaluationException: org.apache.sling.scripting.sightly.SightlyException: Promise has completed with failure: Error: No resource found at path: /var/classes/sightly
```

Note: I installed hobbes js 1.2.5 package to try to satisfy the AEM package dependency.

**Comment by pkg19** [comment]
Getting similar issue while migrating to AEM6.1
org.apache.sling.engine.impl.SlingRequestProcessorImpl service: Uncaught SlingException
org.apache.sling.scripting.sightly.SightlyException: Promise has completed with failure: Error: No resource found at path: /content/xxxxxxxx/xxxxxxxxxxxxxxxxxxx/xxxx/products/jcr:content/mainnav/flyout/spotlight
	at org.apache.sling.scripting.sightly.js.impl.async.AsyncExtractor.decodeJSPromise(AsyncExtractor.java:63)
	at org.apache.sling.scripting.sightly.js.impl.async.AsyncExtractor.extract(AsyncExtractor.java:45)
	at org.apache.sling.scripting.sightly.js.impl.rhino.JsValueAdapter.forceAsync(JsValueAdapter.java:112)
	at org.apache.sling.scripting.sightly.js.impl.rhino.JsValueAdapter.adapt(JsValueAdapter.java:68)
	at org.apache.sling.scripting.sightly.js.impl.rhino.HybridObject.getAdapted(HybridObject.java:79)
	at org.apache.sling.scripting.sightly.js.impl.rhino.HybridObject.getProperty(HybridObject.java:53)
	at org.apache.sling.scripting.sightly.impl.engine.runtime.RenderContextImpl.getProperty(RenderContextImpl.java:278)
	at org.apache.sling.scripting.sightly.impl.engine.runtime.RenderContextImpl.resolveProperty(RenderContextImpl.java:103)

If the spotlight node is not present under flyout, it breaks the entire portal. The portal continued to work in AEM6.0 although the same exception was reported in logs there also.

**Comment by asimarunava** [comment]
Any solution for this??

**Comment by soujiro32167** [comment]
same here...

**Comment by raducotescu** [comment]
This should be fixed in https://github.com/Adobe-Marketing-Cloud/aem-htl-repl/releases/tag/aem-htl-repl-1.0.4.
